# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

# Fabric Properties
minecraft_version=1.21.10
loader_version=0.19.5
loom_version=1.13.4

# Mod Properties
version=1.0.0
group=com.pixelmoji

# Dependencies
fabric_api_version=0.138.0+1.21.10